### PR TITLE
:recycle: Fix semantic-release and @vitest/coverage-v8 versions

### PR DESCRIPTION
**Pull request by antoniovizuete**

### CODE REVIEW

**Comment by LansweeperCloudDevelopment** [comment]
Greetings, Homo Sapiens! :wave:

I've just put your Pull Request code on a testable environment. :rocket:

Test your changes before merging to master.

 Here is your PR Preview [https://nebula-pr-2.pr-preview.lansweeperdev.com](https://nebula-pr-2.pr-preview.lansweeperdev.com) :arrow_upper_right:

**Comment by LansweeperCloudDevelopment** [comment]
Greetings, Homo Sapiens! :wave:

I've just put your Pull Request code on a testable environment. :rocket:

Test your changes before merging to master.

 Here is your PR Preview [https://nebula-pr-2.pr-preview.lansweeperdev.com](https://nebula-pr-2.pr-preview.lansweeperdev.com) :arrow_upper_right:

**Comment by LansweeperCloudDevelopment** [comment]
Greetings, Homo Sapiens! :wave:

I've just put your Pull Request code on a testable environment. :rocket:

Test your changes before merging to master.

 Here is your PR Preview [https://nebula-pr-2.pr-preview.lansweeperdev.com](https://nebula-pr-2.pr-preview.lansweeperdev.com) :arrow_upper_right:

**Comment by antoniovizuete** [comment]
My test comment

**Comment by antoniovizuete** [comment]
Greetings, Homo Sapiens! :wave:

I've just put your Pull Request code on a testable environment. :rocket:

Test your changes before merging to master.

 Here is your PR Preview [https://nebula-pr-2.pr-preview.lansweeperdev.com](https://nebula-pr-2.pr-preview.lansweeperdev.com) :arrow_upper_right:

**Comment by LansweeperCloudDevelopment** [comment]
Greetings, Homo Sapiens! :wave:

I've just put your Pull Request code on a testable environment. :rocket:

Test your changes before merging to master.

 Here is your PR Preview [https://nebula-pr-2.pr-preview.lansweeperdev.com](https://nebula-pr-2.pr-preview.lansweeperdev.com) :arrow_upper_right:

**Comment by LansweeperCloudDevelopment** [comment]
Greetings, Homo Sapiens! :wave:

I've just put your Pull Request code on a testable environment. :rocket:

Test your changes before merging to master.

 Here is your PR Preview [https://nebula-pr-2.pr-preview.lansweeperdev.com](https://nebula-pr-2.pr-preview.lansweeperdev.com) :arrow_upper_right:

**Comment by LansweeperCloudDevelopment** [comment]
Greetings, Homo Sapiens! :wave:

I've just put your Pull Request code on a testable environment. :rocket:

Test your changes before merging to master.

 Here is your PR Preview [https://nebula-pr-2.pr-preview.lansweeperdev.com](https://nebula-pr-2.pr-preview.lansweeperdev.com) :arrow_upper_right:

**Comment by LansweeperCloudDevelopment** [comment]
Greetings, Homo Sapiens! :wave:

I've just put your Pull Request code on a testable environment. :rocket:

Test your changes before merging to master.

 Here is your PR Preview [https://nebula-pr-2.pr-preview.lansweeperdev.com](https://nebula-pr-2.pr-preview.lansweeperdev.com) :arrow_upper_right:

**Comment by LansweeperCloudDevelopment** [comment]
Greetings, Homo Sapiens! :wave:

I've just put your Pull Request code on a testable environment. :rocket:

Test your changes before merging to master.

 Here is your PR Preview [https://nebula-pr-2.pr-preview.lansweeperdev.com](https://nebula-pr-2.pr-preview.lansweeperdev.com) :arrow_upper_right:

**Comment by LansweeperCloudDevelopment** [comment]
Greetings, Homo Sapiens! :wave:

I've just put your Pull Request code on a testable environment. :rocket:

Test your changes before merging to master.

 Here is your PR Preview [https://nebula-pr-2.pr-preview.lansweeperdev.com](https://nebula-pr-2.pr-preview.lansweeperdev.com) :arrow_upper_right:

UNIX Timestamp:1718172781

**Comment by LansweeperCloudDevelopment** [comment]
Greetings, Homo Sapiens! :wave:

I've just put your Pull Request code on a testable environment. :rocket:

Test your changes before merging to master.

 Here is your PR Preview [https://nebula-pr-2.pr-preview.lansweeperdev.com](https://nebula-pr-2.pr-preview.lansweeperdev.com) :arrow_upper_right:

UNIX Timestamp:1718179915

**Comment by LansweeperCloudDevelopment** [comment]
Greetings, Homo Sapiens! :wave:

I've just put your Pull Request code on a testable environment. :rocket:

Test your changes before merging to master.

 Here is your PR Preview [https://nebula-pr-2.pr-preview.lansweeperdev.com](https://nebula-pr-2.pr-preview.lansweeperdev.com) :arrow_upper_right:

UNIX Timestamp:1718180108

**Pull request closed without merging**
